[package]
name = "common-pipeline-transforms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../../common/base" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-pipeline-core = { path = "../core" }
common-profile = { path = "../../profile" }
cpu-time = "0.1"
match-template = "0.0.1"

async-backtrace = { workspace = true }
async-trait = { version = "0.1.57", package = "async-trait-fn" }

[package.metadata.cargo-machete]
ignored = ["match-template"]
